name: Build and Publish Plugins and Themes

on:
    push:
        paths:
            - .github/**
            - Plugins/**
            - Themes/**
            - build.sh
            - LICENSE
            - README.md

permissions:
    contents: write

jobs:
    build_and_publish:
        name: Build and Publish Plugins and Themes
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: "0"

            - name: Install node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x

            - name: Install repository dependencies
              run: npm ci

            - name: Build themes
              run: |
                  npm run build-theme
                  cp -r Themes/PlexBetterStyles/PlexBetterStyles.yml dist/Themes/PlexBetterStyles/

            - name: Move plugins
              run: cp -r Plugins dist/Plugins/

            - name: Run build.sh
              run: |
                  chmod +x ./build.sh
                  ./build.sh

            - name: Move license and readme.md
              run: cp -r README.md LICENSE dist/builds/

            - name: Publish to dist branch
              uses: s0/git-publish-subdir-action@develop
              env:
                  REPO: self
                  BRANCH: dist
                  FOLDER: "dist/builds"
                  MESSAGE: "built for {sha}"
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
