name: Build and Publish Theme

on:
    push:
        paths:
            - .github/**
            - Themes/**
    pull_request:
        paths:
            - .github/**
            - Themes/**

jobs:
    build_and_publish:
        name: Setup Linux environment
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20.x

            - name: Install repository dependencies
              run: npm ci

            - name: Build theme
              run: npm run build-theme

            - name: Publish theme
              uses: s0/git-publish-subdir-action@develop
              env:
                  REPO: self
                  BRANCH: dist
                  FOLDER: "dist"
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
